# https://github.com/mitchellh/vagrant-google
#TODO: variables
Vagrant.configure("2") do |config|

  config.vm.define "gcp" do |gcp|
    gcp.vm.box = "google/gce" #dummy gcp vagrantbox provided by atlas
    config.vm.provider :google do |google, override|
      google.google_project_id = "../sa.json" #from terraform
      google.google_json_key_location = "" #terraform service account key.json
      google.image_family = "kali-rolling"
      google.name = "kali-v1.0"
      google.disk_size = 500                 
      google.machine_type = "n1-standard-4"
      override.ssh.username = 'provisioner'
      override.ssh.private_key_path = 'id_rsa.pub' # your ssh key
    end
  end

  config.vm.provision "shell", path: "scripts/create-swapfile.sh"
  config.vm.provision "shell", path: "scripts/install-chrome-remote-desktop.sh"
  config.vm.provision "shell", path: "scripts/all-passwordless-sudo.sh"
  config.vm.provision "shell", path: "scripts/set-hostname-kali.sh"

  config.vm.provision "shell", path: "scripts/pulseaudio.sh"
  config.vm.provision "shell", path: "scripts/install-nessus.sh"
  config.vm.provision "shell", path: "scripts/install-misc-packages.sh"
  config.vm.provision "shell", path: "scripts/install-social-engineer-toolkit.sh"
end
